version: '3.1'

services:
  backend:
    container_name: ngcash_backend
    build: ./backend
    working_dir: /backend
    ports:
      - 3999:3001
    platform: linux/x86_64
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: ngcash_db
    ports:
      - 5999:5432
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    restart: always
